name: PR Gitleaks Comment

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '.gitleaksignore'

permissions:
  pull-requests: write
  contents: read

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: checkout custom actions
        uses: actions/checkout@v4
        with:
          repository: epy0n0ff/gitleaks-diff-comment
          ref: 327b3a0a9011fc6a6c9fa7c3074623690ac510e4
          path: gitleaks-diff-comment
      - name: Comment on .gitleaksignore changes
        uses: ./gitleaks-diff-comment
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ github.event.pull_request.number }}
          debug: 'true'
